/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarVendedora1.java
 *
 * Created on 21/12/2010, 16:21:17
 */
package licrystsystem.vendedora;

import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;
import licrystsystem.main.FramePrincipal;
import licrystsystem.produto.InserirProduto1;

/**
 *
 * @author Diego
 */
public class CadastrarVendedora1 extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;
    private MaskFormatter msk1;
    private MaskFormatter msk2;
    private int n = 0;
    private boolean atualizado = false;

    /** Creates new form CadastrarVendedora1 */
    public CadastrarVendedora1(FramePrincipal framePrincipal) {
        try {
            msk1 = new MaskFormatter("##/##/####");
            msk2 = new MaskFormatter("(##)");
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarVendedora1.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new JFormattedTextField(msk1);
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new JFormattedTextField(msk2);
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new JFormattedTextField(msk2);
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new JFormattedTextField(msk2);
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 =  new JPanel(){
            protected void paintComponent( Graphics g ){
                super.paintComponent(g);
                g.drawImage(framePrincipal.getImagem(), 0, 0, getWidth(), getHeight(), this);
            }
        };

        setLayout(new java.awt.GridLayout(1, 3));

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        jTextField1.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 255));
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome:");

        jButton1.setBackground(new java.awt.Color(102, 0, 51));
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 51));
        jButton2.setForeground(new java.awt.Color(102, 0, 51));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 51, 255));
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Endereço:");

        jTextField2.setBackground(new java.awt.Color(255, 204, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 51, 255));
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("RG:");

        jTextField3.setBackground(new java.awt.Color(255, 204, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(255, 204, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 51, 255));
        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");

        jLabel5.setBackground(new java.awt.Color(255, 51, 255));
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("(não coloque pontos entre os números)");

        jLabel6.setBackground(new java.awt.Color(255, 51, 255));
        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CPF/CIC:");

        jTextField5.setBackground(new java.awt.Color(255, 204, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 51, 255));
        jLabel7.setForeground(new java.awt.Color(255, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");

        jTextField6.setBackground(new java.awt.Color(255, 204, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 51, 255));
        jLabel8.setForeground(new java.awt.Color(255, 204, 255));
        jLabel8.setText("(não coloque pontos entre os números)");

        jLabel9.setBackground(new java.awt.Color(255, 51, 255));
        jLabel9.setForeground(new java.awt.Color(255, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Bairro:");

        jTextField7.setBackground(new java.awt.Color(255, 204, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 51, 255));
        jLabel10.setForeground(new java.awt.Color(255, 204, 255));
        jLabel10.setText("Cidade:");

        jTextField8.setBackground(new java.awt.Color(255, 204, 255));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 51, 255));
        jLabel11.setForeground(new java.awt.Color(255, 204, 255));
        jLabel11.setText("nº:");

        jTextField9.setBackground(new java.awt.Color(255, 204, 255));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 51, 255));
        jLabel12.setForeground(new java.awt.Color(255, 204, 255));
        jLabel12.setText("Complemento:");

        jTextField10.setBackground(new java.awt.Color(255, 204, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 51, 255));
        jLabel13.setForeground(new java.awt.Color(255, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Data de nascimento:");

        jTextField11.setBackground(new java.awt.Color(255, 204, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 51, 255));
        jLabel14.setForeground(new java.awt.Color(255, 204, 255));
        jLabel14.setText("(dd/mm/aaaa)");

        jLabel15.setBackground(new java.awt.Color(255, 51, 255));
        jLabel15.setForeground(new java.awt.Color(255, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Telefone Residencial:");

        jTextField12.setBackground(new java.awt.Color(255, 204, 255));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jTextField13.setBackground(new java.awt.Color(255, 204, 255));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 51, 255));
        jLabel16.setForeground(new java.awt.Color(255, 204, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Telefone Trabalho:");

        jTextField14.setBackground(new java.awt.Color(255, 204, 255));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        jTextField15.setBackground(new java.awt.Color(255, 204, 255));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 51, 255));
        jLabel17.setForeground(new java.awt.Color(255, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Celular:");

        jTextField16.setBackground(new java.awt.Color(255, 204, 255));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });

        jTextField17.setBackground(new java.awt.Color(255, 204, 255));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 51, 255));
        jLabel18.setForeground(new java.awt.Color(255, 204, 255));
        jLabel18.setText("Observações:");

        jLabel19.setForeground(new java.awt.Color(255, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("-");

        jLabel20.setForeground(new java.awt.Color(255, 204, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("-");

        jLabel21.setForeground(new java.awt.Color(255, 204, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("-");

        jButton3.setBackground(new java.awt.Color(102, 0, 51));
        jButton3.setForeground(new java.awt.Color(102, 0, 51));
        jButton3.setText("Consultar tabela de vendedores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("*");

        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("*");

        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("*");

        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("*");

        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("*");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("*");

        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("*");

        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("Os campos marcados com ' * ' devem ser preenchidos obrigatóriamente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addGap(1135, 1135, 1135))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(783, 783, 783))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(83, 83, 83)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField12, jTextField14, jTextField16});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField10, jTextField9});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jTextField3)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5)
                                .addComponent(jLabel7)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jLabel24))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel28))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel10)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField13)
                                .addComponent(jLabel19)))
                        .addGap(1, 1, 1)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(386, 386, 386))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField10, jTextField11, jTextField12, jTextField13, jTextField14, jTextField15, jTextField16, jTextField17, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9});

        add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
}//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        framePrincipal.setContentPane(framePrincipal.getMenuPrincipal());
        framePrincipal.pack();
        framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
}//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty() && !jTextField3.getText().isEmpty() && !jTextField4.getText().isEmpty() && !jTextField5.getText().isEmpty() && !jTextField6.getText().isEmpty() && !jTextField7.getText().isEmpty() && !jTextField8.getText().isEmpty() && !jTextField9.getText().isEmpty() && !jTextField11.getText().isEmpty())) {

            if (getN() == 0) {
                String nome = getjTextField1().getText();

                String RG = getjTextField3().getText() + getjTextField4().getText();

                String CPF = getjTextField5().getText() + getjTextField6().getText();

                String Rua = getjTextField2().getText();

                String Numero = getjTextField9().getText();

                String Comp = getjTextField10().getText();

                String Bairro = getjTextField7().getText();

                String Cidade = getjTextField8().getText();

                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date dataUtil;
                try {
                    dataUtil = new Date(format.parse(getjTextField11().getText()).getTime());

                    java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());
                    String telResidencial = getjTextField12().getText() + " " + getjTextField13().getText();

                    String telTrabalho = getjTextField14().getText() + " " + getjTextField15().getText();

                    String telCelular = getjTextField16().getText() + " " + getjTextField17().getText();

                    String Obs = getjTextArea1().getText();


                    getjTextField1().setText("");
                    getjTextField2().setText("");
                    getjTextField3().setText("");
                    getjTextField4().setText("");
                    getjTextField5().setText("");
                    getjTextField6().setText("");
                    getjTextField7().setText("");
                    getjTextField8().setText("");
                    getjTextField9().setText("");
                    getjTextField10().setText("");
                    ((JFormattedTextField) getjTextField11()).setValue("");
                    ((JFormattedTextField) getjTextField12()).setValue("");
                    getjTextField13().setText("");
                    ((JFormattedTextField) getjTextField14()).setValue("");
                    getjTextField15().setText("");
                    ((JFormattedTextField) getjTextField16()).setValue("");
                    getjTextField17().setText("");
                    getjTextArea1().setText("");

                    try {
                        framePrincipal.getStm().executeUpdate("INSERT INTO VENDEDORA(NOME, RG, CPF, RUA, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, DATANASC, TELLRES, TELTRAB, CELL, OBSERVACAO) VALUES('" + nome + "' , '" + RG + "', '" + CPF + "', '" + Rua + "', '" + Numero + "', '" + Comp + "', '" + Bairro + "', '" + Cidade + "', '" + dataSql + "', '" + telResidencial + "', '" + telTrabalho + "', '" + telCelular + "', '" + Obs + "');");
                        framePrincipal.setContentPane(framePrincipal.getMenuPrincipal());
                        framePrincipal.pack();
                        framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
                        framePrincipal.getCadastrarVendedora1().setAtualizado(false);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao inserir vendedora. Verifique se o RG, nome ou CPF são repitidos");
                    }

                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Erro inesperado");
                }

            } else {
                String nome = getjTextField1().getText();

                String Rua = getjTextField2().getText();

                String Numero = getjTextField9().getText();

                String Comp = getjTextField10().getText();

                String Bairro = getjTextField7().getText();

                String Cidade = getjTextField8().getText();

                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date dataUtil;
                try {
                    dataUtil = new Date(format.parse(getjTextField11().getText()).getTime());

                    java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

                    String telResidencial = getjTextField12().getText() + " " + getjTextField13().getText();

                    String telTrabalho = getjTextField14().getText() + " " + getjTextField15().getText();

                    String telCelular = getjTextField16().getText() + " " + getjTextField17().getText();

                    String Obs = getjTextArea1().getText();
                    try {
                        framePrincipal.getStm().executeUpdate("UPDATE VENDEDORA SET RUA = '" + Rua + "', NUMERO = '" + Numero + "', COMPLEMENTO = '" + Comp + "', BAIRRO = '" + Bairro + "', CIDADE = '" + Cidade + "', DATANASC = '" + dataSql + "', TELLRES = '" + telResidencial + "', TELTRAB = '" + telTrabalho + "', CELL = '" + telCelular + "', OBSERVACAO = '" + Obs + "' WHERE NOME = '" + nome + "';");

                        framePrincipal.getTabelaVendedora().getData().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), dataSql.toString());
                        framePrincipal.getTabelaVendedora().getTelTrab().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), telTrabalho);
                        framePrincipal.getTabelaVendedora().getObs().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), Obs);
                        framePrincipal.getTabelaVendedora().getRuas().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), Rua);
                        framePrincipal.getTabelaVendedora().getNumeros().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), Numero);
                        framePrincipal.getTabelaVendedora().getComps().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), Comp);
                        framePrincipal.getTabelaVendedora().getBairros().set(framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), Bairro);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(Rua + " nº " + Numero + " " + Comp + " " + Bairro, framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), 1);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(Cidade, framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), 2);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(telResidencial, framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), 3);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(telCelular, framePrincipal.getTabelaVendedora().getjTable1().getSelectedRow(), 4);

                        getjTextField1().setText("");
                        getjTextField2().setText("");
                        getjTextField3().setText("");
                        getjTextField4().setText("");
                        getjTextField5().setText("");
                        getjTextField6().setText("");
                        getjTextField7().setText("");
                        getjTextField8().setText("");
                        getjTextField9().setText("");
                        getjTextField10().setText("");
                        ((JFormattedTextField) getjTextField11()).setValue("");
                        ((JFormattedTextField) getjTextField12()).setValue("");
                        getjTextField13().setText("");
                        ((JFormattedTextField) getjTextField14()).setValue("");
                        getjTextField15().setText("");
                        ((JFormattedTextField) getjTextField16()).setValue("");
                        getjTextField17().setText("");
                        getjTextArea1().setText("");
                        framePrincipal.setContentPane(framePrincipal.getTabelaVendedora());
                        framePrincipal.pack();
                        framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
                        jTextField1.setEnabled(true);
                        jTextField3.setEnabled(true);
                        jTextField4.setEnabled(true);
                        jTextField5.setEnabled(true);
                        jTextField6.setEnabled(true);
                        jButton2.setVisible(true);
                        jButton3.setText("Consultar tabela de vendedores");
                        jButton1.setText("Inserir");
                        framePrincipal.getCadastrarVendedora1().setAtualizado(false);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao atualizar dados da vendedora");
                    }

                } catch (ParseException ex) {
                    Logger.getLogger(CadastrarVendedora1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos de texto");
        }


        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            framePrincipal.getTabelaVendedora().setN(1);
            if (n == 3) {
                getjTextField1().setText("");
                getjTextField2().setText("");
                getjTextField3().setText("");
                getjTextField4().setText("");
                getjTextField5().setText("");
                getjTextField6().setText("");
                getjTextField7().setText("");
                getjTextField8().setText("");
                getjTextField9().setText("");
                getjTextField10().setText("");
                ((JFormattedTextField) getjTextField11()).setValue("");
                ((JFormattedTextField) getjTextField12()).setValue("");
                getjTextField13().setText("");
                ((JFormattedTextField) getjTextField14()).setValue("");
                getjTextField15().setText("");
                ((JFormattedTextField) getjTextField16()).setValue("");
                getjTextField17().setText("");
                getjTextArea1().setText("");
                framePrincipal.setContentPane(framePrincipal.getTabelaVendedora());
                framePrincipal.pack();
                framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
                framePrincipal.getCadastrarVendedora1().getjTextField1().setEnabled(true);
                framePrincipal.getCadastrarVendedora1().getjTextField3().setEnabled(true);
                framePrincipal.getCadastrarVendedora1().getjTextField4().setEnabled(true);
                framePrincipal.getCadastrarVendedora1().getjTextField5().setEnabled(true);
                framePrincipal.getCadastrarVendedora1().getjTextField6().setEnabled(true);
                framePrincipal.getCadastrarVendedora1().getjButton2().setVisible(true);
                framePrincipal.getCadastrarVendedora1().getjButton3().setText("Consultar tabela de vendedores");
                framePrincipal.getCadastrarVendedora1().getjButton1().setText("Inserir");

            } else {
                framePrincipal.setContentPane(framePrincipal.getTabelaVendedora());
                framePrincipal.pack();
                framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
                framePrincipal.setRs(framePrincipal.getStm().executeQuery("SELECT V.NOME, V.RG, V.CPF, V.RUA, V.NUMERO, V.COMPLEMENTO, V.BAIRRO, V.CIDADE, V.DATANASC, V.TELLRES, V.TELTRAB, V.CELL, V.OBSERVACAO FROM VENDEDORA V GROUP BY V.NOME, V.RG, V.CPF, V.RUA, V.NUMERO, V.COMPLEMENTO, V.BAIRRO, V.CIDADE, V.DATANASC, V.TELLRES, V.TELTRAB, V.CELL, V.OBSERVACAO;"));
                if (!framePrincipal.getCadastrarVendedora1().isAtualizado()) {
                    int i = 0;
                    framePrincipal.getTabelaVendedora().setRGs(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setCPFs(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setData(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setTelTrab(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setObs(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setRuas(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setNumeros(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setComps(new ArrayList<String>());
                    framePrincipal.getTabelaVendedora().setBairros(new ArrayList<String>());

                    while (framePrincipal.getRs().next()) {
                        if (framePrincipal.getTabelaVendedora().getModeloTabela().getRowCount() < i + 1) {
                            framePrincipal.getTabelaVendedora().getModeloTabela().addRow(new String[framePrincipal.getTabelaVendedora().getModeloTabela().getColumnCount()]);
                        }
                        framePrincipal.getTabelaVendedora().getRGs().add(framePrincipal.getRs().getString("RG"));
                        framePrincipal.getTabelaVendedora().getCPFs().add(framePrincipal.getRs().getString("CPF"));
                        framePrincipal.getTabelaVendedora().getData().add(framePrincipal.getRs().getString("DATANASC"));
                        framePrincipal.getTabelaVendedora().getTelTrab().add(framePrincipal.getRs().getString("TELTRAB"));
                        framePrincipal.getTabelaVendedora().getObs().add(framePrincipal.getRs().getString("OBSERVACAO"));
                        framePrincipal.getTabelaVendedora().getRuas().add(framePrincipal.getRs().getString("RUA"));
                        framePrincipal.getTabelaVendedora().getNumeros().add(framePrincipal.getRs().getString("NUMERO"));
                        framePrincipal.getTabelaVendedora().getComps().add(framePrincipal.getRs().getString("COMPLEMENTO"));
                        framePrincipal.getTabelaVendedora().getBairros().add(framePrincipal.getRs().getString("BAIRRO"));
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(framePrincipal.getRs().getString("NOME"), i, 0);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(framePrincipal.getRs().getString("RUA") + " nº " + framePrincipal.getRs().getString("NUMERO") + " " + framePrincipal.getRs().getString("COMPLEMENTO") + " " + framePrincipal.getRs().getString("BAIRRO"), i, 1);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(framePrincipal.getRs().getString("CIDADE"), i, 2);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(framePrincipal.getRs().getString("TELLRES"), i, 3);
                        framePrincipal.getTabelaVendedora().getModeloTabela().setValueAt(framePrincipal.getRs().getString("CELL"), i, 4);
                        i++;
                    }
                    framePrincipal.getTabelaVendedora().getjTable1().repaint();
                    framePrincipal.getCadastrarVendedora1().setAtualizado(true);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField3().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField3().getText().length() > 7) {
            getjTextField3().setText(getjTextField3().getText().substring(0, 8));
            getjTextField4().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (getjTextField1().getText().length() > 99) {
            getjTextField1().setText(getjTextField1().getText().substring(0, 100));
            getjTextField3().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58) || k == 88 || k == 120) {
        } else {
            if (k == 22) {
                getjTextField4().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField4().getText().length() > 0) {
            getjTextField4().setText(getjTextField4().getText().substring(0, 1));
            getjTextField5().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField5().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField5().getText().length() > 8) {
            getjTextField5().setText(getjTextField5().getText().substring(0, 9));
            getjTextField6().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField6().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField6().getText().length() > 1) {
            getjTextField6().setText(getjTextField6().getText().substring(0, 2));
            getjTextField11().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        if (getjTextField2().getText().length() > 99) { //quando tiver 100 caracteres vai mudar o foco
            getjTextField2().setText(getjTextField2().getText().substring(0, 100));
            getjTextField9().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField9().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField9().getText().length() > 4) {
            getjTextField9().setText(getjTextField9().getText().substring(0, 5));
            getjTextField10().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        if (getjTextField10().getText().length() > 4) { //quando tiver 100 caracteres vai mudar o foco
            getjTextField10().setText(getjTextField10().getText().substring(0, 5));
            getjTextField7().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        if (getjTextField7().getText().length() > 99) { //quando tiver 100 caracteres vai mudar o foco
            getjTextField7().setText(getjTextField7().getText().substring(0, 100));
            getjTextField8().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        if (getjTextField8().getText().length() > 19) { //quando tiver 100 caracteres vai mudar o foco
            getjTextField8().setText(getjTextField8().getText().substring(0, 20));
            getjTextField11().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                ((JFormattedTextField) getjTextField11()).setValue("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField11().getText().length() > 10) {
            ((JFormattedTextField) getjTextField11()).setValue(getjTextField11().getText().substring(0, 10));
            getjTextField12().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                ((JFormattedTextField) getjTextField12()).setValue("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField12().getText().length() > 5) {
            ((JFormattedTextField) getjTextField12()).setValue(getjTextField12().getText().substring(0, 4));
            getjTextField13().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                ((JFormattedTextField) getjTextField14()).setValue("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField14().getText().length() > 5) {
            ((JFormattedTextField) getjTextField14()).setValue(getjTextField14().getText().substring(0, 4));
            getjTextField15().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                ((JFormattedTextField) getjTextField16()).setValue("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField16().getText().length() > 5) {
            ((JFormattedTextField) getjTextField16()).setValue(getjTextField16().getText().substring(0, 4));
            getjTextField17().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField13().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField13().getText().length() > 14) {
            getjTextField13().setText(getjTextField13().getText().substring(0, 15));
            getjTextField14().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField15().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField15().getText().length() > 14) {
            getjTextField15().setText(getjTextField15().getText().substring(0, 15));
            getjTextField16().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                getjTextField17().setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
        if (getjTextField17().getText().length() > 14) {
            getjTextField17().setText(getjTextField17().getText().substring(0, 15));
            getjTextArea1().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        if (getjTextArea1().getText().length() > 499) { //quando tiver 100 caracteres vai mudar o foco
            getjTextArea1().setText(getjTextArea1().getText().substring(0, 500));
            getjButton1().requestFocus();
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_jTextArea1KeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the n
     */
    public int getN() {
        return n;
    }

    /**
     * @param n the n to set
     */
    public void setN(int n) {
        this.n = n;
    }

    /**
     * @return the atualizado
     */
    public boolean isAtualizado() {
        return atualizado;
    }

    /**
     * @param atualizado the atualizado to set
     */
    public void setAtualizado(boolean atualizado) {
        this.atualizado = atualizado;
    }

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * @param jTextArea1 the jTextArea1 to set
     */
    public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    /**
     * @return the jTextField1
     */
    public javax.swing.JTextField getjTextField1() {
        return jTextField1;
    }

    /**
     * @param jTextField1 the jTextField1 to set
     */
    public void setjTextField1(javax.swing.JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    /**
     * @return the jTextField10
     */
    public javax.swing.JTextField getjTextField10() {
        return jTextField10;
    }

    /**
     * @param jTextField10 the jTextField10 to set
     */
    public void setjTextField10(javax.swing.JTextField jTextField10) {
        this.jTextField10 = jTextField10;
    }

    /**
     * @return the jTextField11
     */
    public javax.swing.JTextField getjTextField11() {
        return jTextField11;
    }

    /**
     * @param jTextField11 the jTextField11 to set
     */
    public void setjTextField11(javax.swing.JTextField jTextField11) {
        this.jTextField11 = jTextField11;
    }

    /**
     * @return the jTextField12
     */
    public javax.swing.JTextField getjTextField12() {
        return jTextField12;
    }

    /**
     * @param jTextField12 the jTextField12 to set
     */
    public void setjTextField12(javax.swing.JTextField jTextField12) {
        this.jTextField12 = jTextField12;
    }

    /**
     * @return the jTextField13
     */
    public javax.swing.JTextField getjTextField13() {
        return jTextField13;
    }

    /**
     * @param jTextField13 the jTextField13 to set
     */
    public void setjTextField13(javax.swing.JTextField jTextField13) {
        this.jTextField13 = jTextField13;
    }

    /**
     * @return the jTextField14
     */
    public javax.swing.JTextField getjTextField14() {
        return jTextField14;
    }

    /**
     * @param jTextField14 the jTextField14 to set
     */
    public void setjTextField14(javax.swing.JTextField jTextField14) {
        this.jTextField14 = jTextField14;
    }

    /**
     * @return the jTextField15
     */
    public javax.swing.JTextField getjTextField15() {
        return jTextField15;
    }

    /**
     * @param jTextField15 the jTextField15 to set
     */
    public void setjTextField15(javax.swing.JTextField jTextField15) {
        this.jTextField15 = jTextField15;
    }

    /**
     * @return the jTextField16
     */
    public javax.swing.JTextField getjTextField16() {
        return jTextField16;
    }

    /**
     * @param jTextField16 the jTextField16 to set
     */
    public void setjTextField16(javax.swing.JTextField jTextField16) {
        this.jTextField16 = jTextField16;
    }

    /**
     * @return the jTextField17
     */
    public javax.swing.JTextField getjTextField17() {
        return jTextField17;
    }

    /**
     * @param jTextField17 the jTextField17 to set
     */
    public void setjTextField17(javax.swing.JTextField jTextField17) {
        this.jTextField17 = jTextField17;
    }

    /**
     * @return the jTextField2
     */
    public javax.swing.JTextField getjTextField2() {
        return jTextField2;
    }

    /**
     * @param jTextField2 the jTextField2 to set
     */
    public void setjTextField2(javax.swing.JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    /**
     * @return the jTextField3
     */
    public javax.swing.JTextField getjTextField3() {
        return jTextField3;
    }

    /**
     * @param jTextField3 the jTextField3 to set
     */
    public void setjTextField3(javax.swing.JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    /**
     * @return the jTextField4
     */
    public javax.swing.JTextField getjTextField4() {
        return jTextField4;
    }

    /**
     * @param jTextField4 the jTextField4 to set
     */
    public void setjTextField4(javax.swing.JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    /**
     * @return the jTextField5
     */
    public javax.swing.JTextField getjTextField5() {
        return jTextField5;
    }

    /**
     * @param jTextField5 the jTextField5 to set
     */
    public void setjTextField5(javax.swing.JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    /**
     * @return the jTextField6
     */
    public javax.swing.JTextField getjTextField6() {
        return jTextField6;
    }

    /**
     * @param jTextField6 the jTextField6 to set
     */
    public void setjTextField6(javax.swing.JTextField jTextField6) {
        this.jTextField6 = jTextField6;
    }

    /**
     * @return the jTextField7
     */
    public javax.swing.JTextField getjTextField7() {
        return jTextField7;
    }

    /**
     * @param jTextField7 the jTextField7 to set
     */
    public void setjTextField7(javax.swing.JTextField jTextField7) {
        this.jTextField7 = jTextField7;
    }

    /**
     * @return the jTextField8
     */
    public javax.swing.JTextField getjTextField8() {
        return jTextField8;
    }

    /**
     * @param jTextField8 the jTextField8 to set
     */
    public void setjTextField8(javax.swing.JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    /**
     * @return the jTextField9
     */
    public javax.swing.JTextField getjTextField9() {
        return jTextField9;
    }

    /**
     * @param jTextField9 the jTextField9 to set
     */
    public void setjTextField9(javax.swing.JTextField jTextField9) {
        this.jTextField9 = jTextField9;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.jButton3 = jButton3;
    }
}
