/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InserirProduto1.java
 *
 * Created on 21/12/2010, 12:27:25
 */
package licrystsystem.produto;

import licrystsystem.main.FramePrincipal;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Diego
 */
public class InserirProduto1 extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;

    /** Creates new form InserirProduto1 */
    public InserirProduto1(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 =  new JPanel(){
            protected void paintComponent( Graphics g ){
                super.paintComponent(g);
                g.drawImage(framePrincipal.getImagem(), 0, 0, getWidth(), getHeight(), this);
            }
        };

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insira o código do produto");

        jButton1.setBackground(new java.awt.Color(102, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Consultar tabela para os produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Gerar código para o produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1359, 1359, 1359))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(1319, 1319, 1319))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addGap(71, 71, 71)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(192, 192, 192)
                .addComponent(jButton3)
                .addGap(1269, 1269, 1269))
        );

        add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1568, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        boolean sinalizador = false;
        String preco = "";
        String nome = "";
        if (!jTextField1.getText().isEmpty()) {
        try {

                framePrincipal.setRs(framePrincipal.getStm().executeQuery("SELECT P.NOME, P.PRECO, P.QTDE, P.CODBARRAS FROM PRODUTO P ;"));
                while (framePrincipal.getRs().next()) {
                    if (framePrincipal.getRs().getString("CODBARRAS").toString().equals(jTextField1.getText())) {
                        sinalizador = true;
                        preco = framePrincipal.getRs().getString("PRECO");
                        nome = framePrincipal.getRs().getString("NOME");
                        framePrincipal.getInserirProduto1_2().setQtde(framePrincipal.getRs().getInt("QTDE"));
                        framePrincipal.getInserirProduto1_2().setCod(framePrincipal.getRs().getString("CODBARRAS"));
                    }
                }
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (sinalizador) {
            framePrincipal.setContentPane(framePrincipal.getInserirProduto1_2());
            framePrincipal.pack();
            framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
            framePrincipal.getInserirProduto1_2().getjTextField1().setText(nome);
            framePrincipal.getInserirProduto1_2().getjTextField2().setText(preco);
            framePrincipal.getInserirProduto1_2().getjTextField1().setEnabled(false);
            framePrincipal.getInserirProduto1_2().getjTextField2().setEnabled(false);
            framePrincipal.getInserirProduto1_2().setN(1);
        } else {
            framePrincipal.getInserirProduto1_2().setCod(jTextField1.getText());
            framePrincipal.setContentPane(framePrincipal.getInserirProduto1_2());
            framePrincipal.pack();
            framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
            framePrincipal.getInserirProduto1_2().setN(0);
        }
        jTextField1.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos de texto");
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int i = 100000;
            framePrincipal.setRs(framePrincipal.getStm().executeQuery("SELECT P.CODBARRAS FROM PRODUTO P ORDER BY P.CODBARRAS;"));
            while (framePrincipal.getRs().next()) {               
                if (Long.parseLong(framePrincipal.getRs().getString("CODBARRAS")) == i) {
                    i = i + 1;
                }
            }
            framePrincipal.getInserirProduto1_2().setCod(((Integer) i).toString());
            framePrincipal.getInserirProduto1_2().setN(0);
            framePrincipal.setContentPane(framePrincipal.getInserirProduto1_2());
            framePrincipal.pack();
            framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        framePrincipal.setContentPane(framePrincipal.getMenuPrincipal());
        framePrincipal.pack();
        framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            framePrincipal.getTabelaProdutos().setN(1);
            framePrincipal.setContentPane(framePrincipal.getTabelaProdutos());
            framePrincipal.pack();
            framePrincipal.setExtendedState(FramePrincipal.MAXIMIZED_BOTH);            
            if (framePrincipal.getInserirProduto1_2().isAtualizado()) {
                framePrincipal.setRs(framePrincipal.getStm().executeQuery("SELECT P.NOME, P.CODBARRAS, P.PRECO, P.QTDE, P.QTDECONS FROM PRODUTO P GROUP BY P.NOME, P.CODBARRAS, P.PRECO, P.QTDE, P.QTDECONS;"));
                int i = 0;
                while (framePrincipal.getRs().next()) {
                    if (framePrincipal.getTabelaProdutos().getModeloTabela().getRowCount() < i + 1) {
                        framePrincipal.getTabelaProdutos().getModeloTabela().addRow(new String[framePrincipal.getTabelaProdutos().getModeloTabela().getColumnCount()]);
                    }
                    framePrincipal.getTabelaProdutos().getModeloTabela().setValueAt(framePrincipal.getRs().getString("NOME"), i, 0);
                    framePrincipal.getTabelaProdutos().getModeloTabela().setValueAt(framePrincipal.getRs().getString("CODBARRAS"), i, 1);
                    framePrincipal.getTabelaProdutos().getModeloTabela().setValueAt("R$ " + framePrincipal.getRs().getString("PRECO"), i, 2);
                    framePrincipal.getTabelaProdutos().getModeloTabela().setValueAt(framePrincipal.getRs().getString("QTDE"), i, 3);
                    framePrincipal.getTabelaProdutos().getModeloTabela().setValueAt(framePrincipal.getRs().getString("QTDECONS"), i, 4);
                    i++;
                }
                framePrincipal.getTabelaProdutos().getjTable1().repaint();
                framePrincipal.getInserirProduto1_2().setAtualizado(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        int k = evt.getKeyChar();
        if ((k > 47 && k < 58)) {
        } else {
            if (k == 22) {
                jTextField1.setText("");
            }
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
